### ISSUE TITLE
Improvements ?

### ISSUE THREAD

**Issue by MGREMY** [tomavic/demo-angular-for-beginners#1]
Hey, just was passing here randomly, I think you can use the new `@if` `@for` syntax in the app.component.html :)

**Comment by tomavic** [comment]
Hi @MGREMY I was just building this demo one by one. The idea was to introduce a simple demo with the known and popular old syntax and then show the new syntax over the time. 

I am making a 2min reels on TikTok and Instagram for that, targeting the beginners. 
Maybe we can discuss that on discord channel 😁

**Comment by MGREMY** [comment]
Oh okay I see I see, nice mindset yeah
Of course we can talk about that on discord, here's my discord : epsilonehd (epsilonehd#0752) :D
